Update patch set 1
Patch Set 1:

I'm getting this now:
external/okhttp/okhttp/src/main/java/com/squareup/okhttp/TcmIdleTimerMonitor.java:36: error: package com.quicinc.tcmiface does not exist
import com.quicinc.tcmiface.DpmTcmIface;
                           ^
external/okhttp/okhttp/src/main/java/com/squareup/okhttp/TcmIdleTimerMonitor.java:41: error: cannot find symbol
public class TcmIdleTimerMonitor implements DpmTcmIface {
                                            ^
  symbol: class DpmTcmIface
external/okhttp/okhttp/src/main/java/com/squareup/okhttp/TcmIdleTimerMonitor.java:61: error: cannot find symbol
          mTcmRegisterMethod = tcmClass.getDeclaredMethod("registerTcmMonitor", DpmTcmIface.class);
                                                                                ^
  symbol:   class DpmTcmIface
  location: class TcmIdleTimerMonitor
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors


Is anything missing ?

Patch-set: 1
Reviewer: LorD ClockaN <1458@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0